
# in case the camera moves you can apply this offset as correction 
calibration:
  x: 280
  y: 30

# per sensor define a list of boxes (as array in order left,top,right,bottom) for the digits from left 
# to right.
sensors:
  kollektor:
    - digit_box:
      - 70
      - 600
      - 180
      - 760
    - digit_box:
      - 180
      - 600
      - 300
      - 760
    - digit_box:
      - 376
      - 600
      - 506
      - 760

  
  puffer_oben:
    - digit_box:
      - 70
      - 750
      - 190
      - 920
    - digit_box:
      - 180
      - 750
      - 300
      - 920
    - digit_box:
      - 376
      - 750
      - 506
      - 920

  puffer_unten:
    - digit_box:
      - 70
      - 920
      - 190
      - 1080
    - digit_box:
      - 180
      - 920
      - 300
      - 1080
    - digit_box:
      - 376
      - 920
      - 506
      - 1080