
# in case the camera moves you can apply this offset as correction 
calibration:
  x: 0
  y: 0

# per sensor define a list of boxes (as array in order left,top,right,bottom) for the digits from left 
# to right.
sensors:
  kollektor:
    - digit_box:
      - 16
      - 600
      - 136
      - 760
    - digit_box:
      - 136
      - 600
      - 256
      - 760
    - digit_box:
      - 376
      - 600
      - 506
      - 760

  
  puffer_oben:
    - digit_box:
      - 16
      - 780
      - 136
      - 940
    - digit_box:
      - 136
      - 780
      - 256
      - 940
    - digit_box:
      - 376
      - 780
      - 506
      - 940

  puffer_unten:
    - digit_box:
      - 16
      - 960
      - 146
      - 1120
    - digit_box:
      - 136
      - 960
      - 266
      - 1120
    - digit_box:
      - 376
      - 960
      - 506
      - 1120